# Generated by Django 5.2.5 on 2025-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('additional_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
